# Generated by Django 5.2.7 on 2025-10-20 10:30

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255, verbose_name='meta_title')),
                ('meta_description', models.CharField(max_length=255, verbose_name='meta_description')),
                ('blog_title', models.CharField(max_length=255, verbose_name='blog_title')),
                ('content', ckeditor.fields.RichTextField()),
                ('content_view', models.ImageField(upload_to='blog_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='thegusto_main.basemodel')),
                ('mail_address', models.CharField(max_length=255, verbose_name='mail_address')),
            ],
            bases=('thegusto_main.basemodel',),
        ),
    ]
