# Generated by Django 5.2.7 on 2025-10-20 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegusto_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
