# Generated by Django 5.2.7 on 2026-01-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegusto_main', '0002_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleryImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_alt', models.CharField(max_length=500, verbose_name='meta_alt')),
                ('image', models.ImageField(upload_to='galery/', verbose_name='resim')),
                ('priority', models.IntegerField(default=9999999, verbose_name='siralama')),
            ],
        ),
    ]
